Add workflow selection and tiny UI improvements
sanity-io/sanity-translations-tab pull request #8
Opened 2022-02-01 01:39 UTC by apennell

- Adds an optional `workflowOptions` param to the config passed to
TranslationsTab from the studio, which accepts an array of workflows.
Workflows are expected to include a `workflowUid`, which can be found
in the Smartling project's UI, and a `workflowName` for display title.
- The workflow select input only shows if at least one workflow option
is passed, and otherwise the additional work of setting the workflow
and locales in task creation isn't done
- The selected workflowUid string (if present) is passed as a param
with the rest of the context to the adapter's `createTask` function
- This replaces the `isWorkflowMT` boolean, allowing user to pass in
one or more specific workflow uids and names.

Example of the config in deskStructure, using `workflowOptions`:
```
const myCustomConfig = {
  ...defaultFieldLevelConfig,
  workflowOptions: [
    { workflowUid: 'abc123', workflowName: 'Machine Translation (testing)' }
  ]
}
```

Also updates styling and layout to add more spacing between sections 
and use appropriate headers to more clearly delineate the form and the 
progress sections, and the sections within the form.

![Screen Shot 2022-01-19 at 3 41 33 PM](https://user-images.githubusercontent.com/11039888/150235988-68eab04e-8054-4a92-af9b-8bcbbfa5c25b.png)
Note: this screenshot is of a studio with custom theming, so if any colors look
off, that's likely why. I did make changes to some of the tones used where it
seemed appropriate, such as the locale labels in the toggle boxes.

2022-02-02 22:42 UTC, cngonzalez requested changes
This looks great! I made annoying fiddly suggestions just based on default studio styling -- let me know if that works for you.

2022-02-02 22:42 UTC, cngonzalez commented on package.json
> +  "version": "2.0.0",
```suggestion
  "version": "2.0.0",
  "version": "1.2.0"
```
I know I initially said we might have to go up a version, but I don't think this is a breaking change (and I have plans for 2.0.0 actually being a breaking change, so I don't want to cause too much noise). Think we can stay in the 1s!

2022-02-02 22:42 UTC, cngonzalez commented on src/components/NewTask.tsx
> +  Heading,
```suggestion
```
We tend not to use Headings in the studio context. I've replaced them with Text as h2s (understandable if this doesn't make sense with your styling, just trying to stay consistent with our own packages!)

2022-02-02 22:42 UTC, cngonzalez commented on src/components/NewTask.tsx
> +          <Text size={1}>{locale.description}</Text>
```suggestion
 <Text size={1} weight="semibold">{locale.description}</Text>
 ```
 
 A bit light in default styling, would like to keep it readable.

2022-02-02 22:42 UTC, cngonzalez commented on src/components/NewTask.tsx
> +      <Heading as="h2" weight="semibold" size={2}>
```suggestion
      <Text as="h2" weight="semibold" size={2}>
```
See above comments on standards in `Heading` vs `Text`

2022-02-02 22:42 UTC, cngonzalez commented on src/components/NewTask.tsx
> +      </Heading>
```suggestion
      </Text>
```

2022-02-02 22:42 UTC, cngonzalez commented on src/components/TaskView.tsx
> +import { Box, Heading, Stack, useToast } from '@sanity/ui'
```suggestion
import { Box, Text, Stack, useToast } from '@sanity/ui'
```
See above comments on standards in `Heading` vs `Text`

2022-02-02 22:42 UTC, cngonzalez commented on src/components/TaskView.tsx
> +      <Heading as="h2" weight="semibold" size={2}>
```suggestion
      <Text as="h2" weight="semibold" size={2}>
```
See above comments on standards in Heading vs Text

2022-02-02 22:42 UTC, cngonzalez commented on src/components/TaskView.tsx
> +      </Heading>
```suggestion
      </Text>
```

2022-02-04 17:51 UTC, apennell commented
Those suggestions are fine and I went ahead and applied them. Thanks!

2022-02-07 20:55 UTC, cngonzalez requested changes
I think some of the suggestions didn't make it through! I put comments where that happened.

2022-02-07 20:55 UTC, cngonzalez commented on src/components/NewTask.tsx
> +      <Heading as="h2" weight="semibold" size={2}>
Sorry, I don't think the <Text> suggestion made it into the code -- would you mind applying it?

2022-02-07 20:55 UTC, cngonzalez commented on src/components/NewTask.tsx
> +          <Text size={1}>{locale.description}</Text>
Sorry I don't think the "semibold" suggestion made it into the code, would you mind applying it?

2022-02-07 20:55 UTC, cngonzalez commented on package.json
> +  "version": "2.0.0",
I messed up my suggesting by including 2 versions :/ would you mind applying this new one?

2022-02-07 22:10 UTC, apennell commented
Sorry about that @cngonzalez! First time accepting suggestions in GH and probably skipped a step. Should be good now, though.

2022-02-14 20:33 UTC, cngonzalez approved these changes

2022-02-14 20:42 UTC, merged